RISCV_ARCH := rv32i
RISCV_ABI := ilp32
RISCV_MCMODEL := medlow


SRC_DIR = src
BUILD_DIR = build
VPATH = $(SRC_DIR)

TARGET = app

C_SRCS := \
	main.c \
	uart.c \
	xprintf.c \
	trap_handler.c

include Makefile.common

